title: Kids Academy
url: "https://kidsacademy.dev"
baseurl: ""
google_analytics_key:
google_maps_javascript_api_key:
disqus_shortname:

description: Uma comunidade de tecnologia focada em Educação para Jovens e Adolescentes

author:
  name:
  email:
  twitter:

social:
  name: Kids Academy
  links:
    - https://kidsacademy.dev

timezone: Etc/UTC

collections:
  mentores:
    output: false
  projetos:
    output: true

paginate: 10
paginate_path: "/blog/:num/"
permalink: pretty

jekyll-archives:
  enabled:
    - "categories"

plugins:
  - "jekyll-feed"
  - "jekyll-seo-tag"
  - "jekyll-paginate"
  - "jekyll-archives"

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

defaults:

  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      _options:
        content:
          width: 960
          height: 2000

  - scope:
      path: ""
      type: "projetos"
    values:
      layout: "projetos"
      _options:
        image_path:
          width: 600
          height: 600

  - scope:
      path: ""
      type: "mentores"
    values:
      _options:
        image_path:
          width: 600
          height: 600

  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

  - scope:
      path: "index.html"
      type: "pages"
    values:
      layout: "default"

social_icons:
  - Facebook
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - RSS
  - GitHub